#!/bin/bash

function install_yay(){
    sudo pacman -Syy
    sudo pacman -S --needed base-devel git --noconfirm
    git clone https://aur.archlinux.org/yay.git
    (cd yay && makepkg -si PKGBUILD && rm -rf ../yay)
}

DIR="$HOME"/programs
sudo pacman -S $(cat "$DIR"/.pacman.list)

pacman -Qq yay 2> /dev/null
# if yay is not installed
if [[ "$?" -ne 0 ]];then 
    install_yay
fi

yay -S $(cat "$DIR"/.yay.list)
