#!/bin/bash


#vim config

#install vim-plug
sh -c 'curl -flo "${xdg_data_home:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

#install plugins in vim from terminal
nvim -c 'PlugInstall'

#coc (auto complete) languages servers

#coc needs node
#install node
sudo pacman -S nodejs npm --noconfirm
sudo npm i -g npm n
sudo n lts

#languages servers
nvim -c 'CocInstall coc-sh coc-pyright coc-java coc-tsserver coc-html coc-clangd coc-phpls'


