#!/bin/bash

DIR="$HOME/programs"

pacman -Qqt > "$DIR"/packages.list
pacman -Qqtm > "$DIR"/.yay.list
pacman -Qqtn > "$DIR"/.pacman.list

# remove ignore packages
cat "$DIR"/.yayignore | xargs -I {} sed -i '/^{}$/d' "$DIR"/.yay.list
