#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

BACKGROUND="#252422"
FOREGROUND="#404D39"
BLUE="#28A6EB"
RED="#66101F"


## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7' '8' '9'
		let name++
	done
}



workspaces

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

############REGLAS PERSONALIZADAS################
# remove all rules first
bspc rule -r *:*


#[[[[ PERSONALIZADAS  ]]]]
bspc rule -a Galculator state=floating
bspc rule -a 'VirtualBox Manager' state=floating
bspc rule -a Zathura state=tiled

# 1 > terminal
#bspc rule -a Alacritty desktop='^1' follow=on focus=on
#bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

# 2 > web
declare -a web=(firefox chromium Google-chrome)
for i in ${web[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

# 3 > pdf
declare -a documents=(Zathura zathura)
for i in ${documents[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > notes
declare -a notes=(obsidian)
for i in ${notes[@]}; do
   bspc rule -a $i desktop='^4' state=fullscreen follow=on focus=on; done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done


# 7 > Communication
declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

# 8 > Music
#bspc rule -a 'VirtualBox Manager' follow=on focus=on
#bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on

# 9 > files: abrir el explorador en el escritorio 9
bspc rule -a "Pcmanfm" desktop='^9' state=fullscreen follow=off locked=on -o
#-o one shot; regla que solo se ejecuta una vez

#bspc rule -a GParted desktop='^8' follow=on focus=on
#declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
#System-config-printer.py Pavucontrol Exo-helper-1 \
#Xfce4-power-manager-settings)
#for i in ${settings[@]}; do
#   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

#[[[[[[[ FLOAT WINDOWS ]]]]]]] 
declare -a floating=(alacritty-float Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off


## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
#xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg
nitrogen --restore &

# Start mpd
#exec mpd &

# Start bspwm scripts
bspcolors
bspbar
bspcomp
bspfloat &

#Star desktop
pcmanfm $HOME/Escritorio &

#variety
variety &

#Change keyboard layout
setxkbmap -option grp:alt_shift_toggle latam,us -variant intl &



